#!/usr/bin/python3
import sys,os
import time
from stat import S_ISDIR, S_ISLNK, S_ISREG, S_ISSOCK, S_ISBLK, S_ISCHR, S_ISFIFO
file_names = sys.argv[1:]
print(file_names)
for i in file_names:
    try:
        os.stat(i)
    except OSError:
            f = open(i,'w')
            f.close()
    os.utime(i)
# it must not replace any existing files
# if there is an existing directory/file than it must not throw an error
# if there is a object than update current time but do not edit this file

